name: backend-workflow-ci

# Triggers
on:
    # Manual trigger using the workflow_dispatch event
    workflow_dispatch:
    # Automatic trigger on pull request events targeting the main branch
    pull_request:
        branches:
            - main
        paths: backend/**

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code source backend
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install Dependencies
              run: |
                  pip install --upgrade pipenv
                  cd backend
                  pipenv install flake8
                  pipenv install

            - name: Run linting
              run: |
                  cd backend
                  pipenv run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code source backend
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install Dependencies
              run: |
                  pip install --upgrade pipenv
                  cd backend
                  pipenv install

            - name: Run test
              run: |
                  cd backend
                  pipenv run test

    build:
        runs-on: ubuntu-latest
        needs: [linting, test]
        environment: admin
        steps:
            - name: Checkout code source backend
              uses: actions/checkout@v3

            - name: Build docker
              env:
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  cd backend
                  docker build --tag "backend:$IMAGE_TAG" .
